### ISSUE TITLE
Make sidecar's dependency on leiningen explicit

### ISSUE THREAD

**Issue by lorddoig** [bhauman/lein-figwheel#151]
With respect to this function in `sidecar`:

```clojure
;; assumes leiningen 
(defn project-unique-id []
  (let [f (io/file "./project.clj")]
    (or (when (.exists f)
          (let [[_ name version] (-> f slurp read-string)]
            (when (and name version)
              (str name "--" version))))
        (.getCanonicalPath (io/file ".")))))
```

Leiningen allows dynamic evaluation, e.g.

```clojure
:checkout-deps-shares ^:replace [:source-paths :resource-paths :compile-path
                                   #=(eval leiningen.core.classpath/checkout-deps-paths)]
```

This thing allows you to pull in checkout dependencies except their test dependencies, which can ordinarily be a right pain.  But this doesn't work when `leiningen.core.classpath` is not on the classpath, which seems to be the case with figwheel (even invoked with lein-figwheel).

It's simple enough (ish) to work around but I think the facts that `project.clj` files a) allow `eval`ing in the spec; and b) are intimately associated with leiningen make it reasonable to assume that any calls to `eval` inside one may well require leiningen to be on the classpath.

**Comment by bhauman** [comment]
It throws a class not found exception because leiningen isn't required by
figwheel.sidecar.

I'm trying very hard not to make the core of figwheel depend on
leiningen. I would have to have lein running in the same process as the
compile process and I really don't thing that this is a good idea.

This case can be eliminated by fetching the id in the lein environment
and passing the data into the figwheel environment.

But unfortunately I just added build config reloading in
figwheel-sidecar/repl.clj. This also reads the project.clj to reload
changes in the build configs.

Neither of these features require the leiningen libraries per se but are
just feature enhancements if the project.clj exists.

This is a tough one, I can fix the project id bug, as for the build config
reloading bug, I'll probably just catch it and continue on.

It's too bad project definitions aren't simply data or separated into
executable.clj / config.edn.

**Comment by bhauman** [comment]
Actually, right now you can supply a `:unique-id "something-unique"` to your root level `:figwheel` config and it should short circuit this code.

**Comment by lorddoig** [comment]
Good to know!  I'm currently resolving the var in a try/catch.

I suppose one idea that might help but not solve the situation is to catch the exception and have another go at reading with `*read-eval*` bound to false, but that in itself could lead to some weird edge cases.
