### ISSUE TITLE
live reloading tests

### ISSUE THREAD

**Issue by murtaza52** [bhauman/lein-figwheel#162]
Hi,

Thanks for the great project ! I watched your video and am having trouble replicating two aspects of it - 
1. Having multiple builds - the :main build and the :test build compile at the same time.  
2. How did you make the results of your test build appear in the browser and make them reload on code changes ? What test runner are you using to see their results in the browser ?

I am newbie so sorry if the questions are too basic. 

Thanks,
Murtaza

**Comment by bhauman** [comment]
Have a look at this project to see how the tests are set up.

https://github.com/bhauman/crashverse

**Comment by wilkerlucio** [comment]
hi @bhauman,

I did copy the code the crashverse, but at least here I still can't figure out how to broadcast multiple builds at once (it only broadcasts the current one on focus, I have to manually run a `(switch-to-build ...)` in order to get a different one to autoreload).

Another issue that I noticed is that when I add new tests (a new `(deftest ...)` entry) it doesn't seems to get the file... even after restarting Figwheel it's not enough, I actually have to delete the output test build and compile it again in order to new tests to be catch up, do you know why is that?

Thanks.

**Comment by bhauman** [comment]
To get this to work in the CrashVerse setup you have to run 
Lein Figwheel dev test

To have both builds building at the same time.

**Comment by murtaza52** [comment]
Yes that was my question too ! Thanks for asking it. Maybe that can be
added to the docs.

**Comment by worace** [comment]
I had been struggling to get a setup like this and this thread helped point me in the right direction -- glad I came across it.

I put together a bare-bones sample project that includes the dev/test build setup with figwheel's autoloading in case it's helpful to anyone else: https://github.com/worace/lein-cljs-testing-example
