### ISSUE TITLE
Pretty print output in figwheel REPL

### ISSUE THREAD

**Issue by tslocke** [bhauman/lein-figwheel#182]
Now that we have cljs.pprint, is there a switch somewhere to turn on pretty-printing the output of the figwheel REPL?

**Comment by bhauman** [comment]
I think this is a great idea.  Should it be a switch or should we just have it on all the time?

**Comment by tablatom** [comment]
On all the time would be better than nothing, certainly. I guess the ideal would be a hook to set the print function.

**Comment by bhauman** [comment]
Actually this has nothing to do with the client side.  You can pass in a `:print` parameter to the cljs.repl/repl function.  This parameter takes one argument and prints to output.

https://github.com/bhauman/lein-figwheel/blob/master/sidecar/src/figwheel_sidecar/repl.clj#L174

If you want to experiment and submit a patch I am open to it.

**Comment by tablatom** [comment]
I will happily experiment with this. Could you give me any tips on setting up figwheel for hacking on it? I've never done any lein plugin development. Thanks.

**Comment by bhauman** [comment]
The real trick is to enable the `:figwheel :nrepl-port` and the connect to it.  
Then reload the changed clojure code `repl.clj` into the nrepl. 
Then in the figwheel-cljs-repl call `(reset-autobuild)` to make sure that the new code is in use.

Thats how I do it :)

**Comment by tablatom** [comment]
I always connect to figwheel via the nrepl-port, as I use the figwheel repl from inside Cursive, but this part:

> Then reload the changed clojure code repl.clj into the nrepl.

has me stumped. I know neither how to locate that file nor how to reload it : ) I've cut my teeth entirely on clojurescript, only touching clojure for macros, so I probably have some gaping holes in my basic clojure knowledge.

**Comment by bhauman** [comment]
Hey I would try doing a little Clojure work first then.  Cursive should
make it easy. Haven't used it though, but ask on the forums and people will
help you out for sure.

https://clojurians.slack.com

**Comment by otijhuis** [comment]
I've been looking into it yesterday and figured the `:print` parameter should be easy enough. Yet I can't get it to work, or at least it doesn't work like I expected :). Probably something obvious I'm missing.

I tried the following (tested it by using `lein figwheel` and eval'ing some stuff that should be pretty printed):

Added the `:print` parameter to the new multimethod.
As the parameter value I tried several things:
- `cljs.pprint/pprint` doesn't work because it doesn't exist in the Clojure space (no .cljc)
- `'cljs.pprint/pprint` gives no errors but nothing whatsoever is printed in the cljs repl
- `clojure.pprint/pprint` returns all output as a string and not pretty printed

I assume the value passed to `:print` should be evaluated in ClojureScript but you start the repl from Clojure. ClojureScript has no vars and such so resolve isn't an option either.

@bhauman : any ideas? Might be totally looking at it the wrong way.

**Comment by bhauman** [comment]
Actually, I seem to remember that there is a bunch more to it.  You need to follow the value back from the the client.cljs. And see where it goes. 

Is it possible to pprint it before we return it? That may be an easier route.

**Comment by bhauman** [comment]
Actually I'm not sure about any of this :)

**Comment by otijhuis** [comment]
Haha, why is it that the things that look so easy are always the ones that make you pull your hair out? :)

No wonder I don't have any left.

**Comment by tablatom** [comment]
What about automatically wrapping each input in `(pprint ...)`? Would that be easier to implement? If the wrapping form was configurable I'd be a happy bunny.
