### ISSUE TITLE
All builds rather than first build

### ISSUE THREAD

**Issue by TerjeNorderhaug** [bhauman/lein-figwheel#220]
With no arguments on the command line, figwheel currently defaults to the first build in the project with optimizations set to none. I propose figwheel instead defaults to all builds with optimizations set to none.

This will facilitate using figwheel for "isomorphic" development with multiple simultaneous cljs builds. A real world scenario is connecting figwheel concurrently to a clojurescript based nodejs server and browser app, without having to specify each of the builds on the command line.

The modification involves deleting the call to #'first in figwheel-sidecar.config/narrow-builds*.

**Comment by bhauman** [comment]
Neat idea but ...

I don't understand why this is needed instead of supplying the builds you want.  I try to make the default the action that **most people** want when they execute `lein figwheel`. The isomorphic situation is still a very minority position.  When you want multiple builds `lein figwheel app server` or `lein figwheel app test` works very well and there is a compile time impact for each additional build which increases notification latency so if `lein figwheel` is greedy and starts `app` `server` and `test`. Is that what you expect and want?

This would require folks to go out of their way to stop the extra builds from auto building.

**Comment by bhauman** [comment]
Also take a look at lein aliases  https://github.com/technomancy/leiningen/blob/master/sample.project.clj#L204

**Comment by jcw** [comment]
@TerjeNorderhaug - maybe something like this can be used in your cljsnode project?

    :aliases {"launchboth" ["figwheel" "app" "server"]}

I would think that launching all is mostly likely _not_ what you want in figwheel projects with both "dev" and "prod" builds in them, for example.

**Comment by bhauman** [comment]
I'm going to close this
