### ISSUE TITLE
rlwrap doesn't seem to work

### ISSUE THREAD

**Issue by danielcompton** [bhauman/lein-figwheel#228]
I'm running OS X 10.10.5 with rlwrap 0.42 installed.

I run a figwheel REPL like:

```sh
rlwrap lein figwheel
```

and figwheel starts up, and connects to the browser. I try to type commands but it doesn't seem to be getting them. It's a little hard to explain, so I attached a gif.

![rlwrap](https://cloud.githubusercontent.com/assets/811954/9592211/1e5f15a0-5095-11e5-8e38-97a9ce46bb2e.gif)

I created that with http://www.cockos.com/licecap/ in case future passers by are interested.

**Comment by bhauman** [comment]
This is weird.  I have no insight here.  I use iTerm and the behavior may be different.  I'm using different versions as well.  The launched cljs repl is a pure io process with no readline interpretation. 

So this is all terminal and rlwrap which I don't have control over.

**Comment by danielcompton** [comment]
I'm using iTerm 2 as well. What versions are you using?

**Comment by bhauman** [comment]
I'm using iTerm2 really not easy to find the build. I'm not using the
latest one though.

**Comment by danielcompton** [comment]
I've found the issue. I had

```sh
stty stop ^j
```

in my `.bashrc` file. I think I put it there because of http://askubuntu.com/questions/60071/how-to-forward-search-history-with-the-reverse-i-search-command-ctrlr a while ago. Removing that line fixes things for me. Sorry for the distraction!

**Comment by eggsyntax** [comment]
I have the same problem, and I'm not customizing the ^j character as @danielcompton was. I haven't been able to track it down on mine. I could go into all the things I've tried to diagnose/fix, but rather than do that, I'm just here to report a reasonable workaround: using socat instead of rlwrap.

You can get socat with `brew install socat` or from http://www.dest-unreach.org/socat/

This command will connect readline and figwheel (saving history in ~/.figwheel_history):
`socat READLINE,history=$HOME/.figwheel_history SYSTEM:"lein figwheel"`

I've got that aliased to 'figwheel', of course ;)

**Comment by danielcompton** [comment]
@eggsyntax try moving all of your dotfiles elsewhere and running with rlwrap again, there's a decent chance you've got something in there that's conflicting.

**Comment by danielcompton** [comment]
If you haven't already, it sounds like you've done quite a lot of troubleshooting.

**Comment by eggsyntax** [comment]
Yeah, my first suspicion was something in my .inputrc, but I tried both moving my dotfiles and, eventually, creating new vanilla user account. No luck. At this point, I suspect some little system-level utility file I installed and then forgot, since it's specific to this box (my other box doesn't have the problem, and I have a pretty stereotyped setup routine & a repo for dotfiles etc). But socat has turned out to be a totally fine solution, so I probably won't try to track it down further. Plus I'm actually pretty psyched to learn about socat, that's a totally badass tool :)
