### ISSUE TITLE
Tags for versions

### ISSUE THREAD

**Issue by weavejester** [bhauman/lein-figwheel#267]
It would be nice if there was some way of finding out which commit corresponds to a particular Figwheel version. There aren't any tags for later Figwheel versions on Github, and Clojars says that the commit for 0.4.1 is simply "HEAD".

**Comment by bhauman** [comment]
You got it. Will the github release feature meet this need?

Also have you seen the Sidecar Readme?  Thoughts?

**Comment by weavejester** [comment]
Well, any way of letting me know what code I'm running would be good :). I was debugging an issue with the piggieback REPL, and it took way longer than usual to find the relevant source code.

Regarding the README, it overall looks pretty good. I only noticed a few things:

1. The `build-switching-cljs-repl` function has a lot of STDOUT when it's run that I can see getting annoying if I keep switching back and forth between Clojure and ClojureScript REPLs.

2. Usually the system is put in a raw var, rather than an atom, during development. But for an example it seems reasonable.

3. You have `rlwrap lein run -m clojure.main` for starting the REPL, instead of `lein repl`, and I don't understand why.

**Comment by bhauman** [comment]
1) That is a good point. Maybe just show the docs the first time.

2) yeah I get it about the raw var. I've been wondering about this a bit. I
have to pass a mutable something to the repl for the system control
functions (clean-builds, etc) that alter the system from inside the cljs
repl, it could well be a var but whatever I choose I'm kinda stuck with
because the system mutating functions are going to require it and
alter-var-root feels a little funny as it subverts the thread separation of
vars.  But I'm probably going to make it var based. I'm gonna talk with
some folks about it.

3) So this is still a thing. Setting up an nrepl/piggieback CLJS repl is
still non trivial for the uninitiated, and can be a pain for the initiated.
In order to write docs that wont send folks down an nREPL piggieback
nightmarish rabbit hole, I am following David Nolen's lead and doing the
`lein run` option.

I know things have gotten much better on the CLJS nREPL front but mortals
still struggle big time.

**Comment by weavejester** [comment]
Ah, I understand the reasoning behind avoiding `lein repl` now, particularly since I've been struggling somewhat with Piggieback.
