### ISSUE TITLE
cljc incremental compilation times

### ISSUE THREAD

**Issue by piranha** [bhauman/lein-figwheel#340]
Hi! I've recently started converting my codebase from `*.cljs` to `*.cljc` (so that I can render stuff on the JVM). And incremental compilation time went up considerably, from ~2s (on my macbook air) on some quite-often-requested-namespace to ~6s. 

When I start incremental compilation with `cljs.build.api/watch`, I don't see this issue.

Any ideas what could go wrong here?

**Comment by bhauman** [comment]
If you want speedy reloads you need to
:reload-clj-files {:clj true :cljc false}
To your base figwheel config.

The problem is that figwheel is having to do clojure macro reloading as well.  It's hard to figure out what reloading behavior a changed cljc file should have.  If it has a macro in it you need to reload the cljs cljc files that depend on it.  It gets really nuts actually.  But if you turn macro reloading off for cljc files and only put macros in clj files then you only take the hit when you are actually editing macros

**Comment by piranha** [comment]
Oh, that makes sense, thanks! I don't think I have any macros in cljc files and I guess it won't be too hard to refrain from doing that. :)
