### ISSUE TITLE
Preventing orphaned processes (Sass watcher/compiler)

### ISSUE THREAD

**Issue by andrewsuzuki** [bhauman/lein-figwheel#382]
Using the given "SASS watcher" example, hitting Ctrl-C from the repl exits but does not properly shut down, leaving the sass watcher process orphaned. What's the best way to prevent this?

**Comment by darwin** [comment]
For some reason this might be hard to do in Java (due to multi-platform nature of process APIs I guess). If you are on a Mac or some unix system, you could wrap your lein figwheel with a bash script which would do the cleanup under any circumstances.

See my pull request to Cooper project for inspiration:
https://github.com/kouphax/lein-cooper/pull/8/commits/5ff18233f5b2914ebbe3a0d971de00a24d5536f6

It has been rock solid solution for me over last few weeks.

**Comment by bhauman** [comment]
It occurs to me that there should be a lein based data driven way to configure Components like cooper does with processes.

**Comment by bhauman** [comment]
I'm going to close this as it seems a solution has been found.
