### ISSUE TITLE
Figwheel captures Ring handler `println`s in its own log

### ISSUE THREAD

**Issue by samroberton** [bhauman/lein-figwheel#436]
3639557 introduced the `log-output-to-figwheel-server-log` middleware, which binds `*out*` to the Figwheel log writer for the duration of a request.

If you're using a `:ring-handler` to run a server inside the Figwheel process (to support an application which is CLJS on the front-end and CLJ on the back-end), this means that any `println`s you have in your application's own Ring handler also get captured into the Figwheel log -- where previously, they appeared on the console, unaffected by Figwheel's logging needs.

Removing the `:server-logfile` configuration option from `project.clj` doesn't solve the problem, since Figwheel will only log to `*out*` if `:repl false` is specified.  I suppose that *is* an option -- it's not necessarily unreasonable for Figwheel to insist that if you want console logging *and* you want a CLJS REPL, then you have to connect to the REPL over a socket, rather than having it right there on the console.  (If you're doing a significant amount of work at the CLJS REPL, no doubt that's what you do anyway.)

But previously it *was* possible to have `*out*` written to the console and still have the CLJS REPL there in case you wanted it on occasion (but not frequently enough to have a specific setup to launch it).  I suspect losing that ability was unintended.

**Comment by bhauman** [comment]
This was an unintended effect.  But also not super unreasonable as you
suggest.

Meeting everyone's needs with the devserver is nigh impossible, and I'm
striving for a good set of defaults.

You can wrap your handler so that you catch errors and *out* yourself and
direct them where you wish.
But having them go to an unknown location was kinda crappy for most
workflows.

Sorry for the changing this out from under you ...

I'm planning on a more sophisticated internal logging so that you can
decide what messages go where.

But that won't be anytime super soon ...

**Comment by martinskou** [comment]
You can make a closure over the original out in you server.clj code:

```
(let [default-out *out*]
  (defn log [txt]
    (binding [*out* default-out]
      (pprint txt))))
```

**Comment by bhauman** [comment]
I'm thinking `:server-logfile false`

Is a sensible solution here...

**Comment by bhauman** [comment]
I'm going to make :server-logfile false signify that you want your output to go straight to *out*.

But this could be more output than people want.
