### ISSUE TITLE
Make sure that connect script ns has a unique per build name

### ISSUE THREAD

**Issue by sfnelson** [bhauman/lein-figwheel#452]
I have two builds that use the same source paths but have different entry points -- different `:main` and different `:on-jsload`. They use the same output directories (`:output-dir`).

When figwheel reloads it often runs the wrong `:on-jsload` behaviour. Inspecting `figwheel/connect.js` from the browser reveals that it has indeed picked up the behaviour from the wrong build. It looks like this behaviour is racey, whichever build runs last writes its `connect.js` file and clobbers the previous build's file.

I'm using the same `:output-dir` because these builds are both very large (~45 seconds clean). Using the same output dir ensures that they share output caches so the second build takes 1.5 seconds instead of 45 seconds of duplicate effort. I've disabled parallel building so they don't race. I want different entry points when they run in the browser -- one for automated unit tests, one for interactive GUI testing).

I think the bug here is that figwheel writes its connect script to a globally shared namespace rather than a namespace that is unique to the build id. This requires that builds do not share output directories, which I think is an invalid assumption.

**Comment by bhauman** [comment]
Having two builds point to the same :output-to directory is a race condition and is precisely what is causing this problem.  There is nothing in figwheel prevents that from being a problem.

You have one process clobbering files while a client is trying to load them.

Cljsbuild throws an error when you try to autobuild two builds to the same output directory.  So the bug probably is that figwheel should be preventing this in the first place just like cljsbuild.

**Comment by sfnelson** [comment]
There is no race because I've disabled parallel building and they share the same source paths. Removing the ability to do this would add an unnecessary 45 seconds to my build time, please don't do this.

**Comment by bhauman** [comment]
I'm not sure why you wouldn't take the word of the tool developer that there is a problem with sharing the :output-dir between builds.  You put me in the position of having to explain why the *parallel* file watching processes (:parallel-builds is internal to the compiler only) and the asynchronous mode of message sending and compiled asset retrieval can cause you to fetch semi compiled assets because the compiler streams the compilation results to the file. 

I do think you have a point about making sure that the figwheel connect script should honor the idea that a namespace is an identity and not reuse figwheel.connect for each build.

But as of now neither figwheel nor the CLJS compiler supports sharing an output directory with consistent compilation results. And this is not a feature that I'm going to explore in the near future.

Your *initial* build time is 45 seconds but your incremental builds are fast.  You are trading a fast initial build time for possible compiled asset inconsistencies on every file save.

If you really want a fast initial build time. Make a script to compile/initialize your assets and copy them before you start. Then your incremental builds will work just fine and more importantly will be consistent and correct.

I still have to consider preventing this behavior in the configuration validation.  You can always turn  config validation off with `:validate-config false`

How often are you building from a clean build?




 



Yes your initial build will

**Comment by bhauman** [comment]
https://github.com/emezeske/lein-cljsbuild/blob/master/plugin/src/leiningen/cljsbuild/config.clj#L125

**Comment by sfnelson** [comment]
You're right about the possibility of retrieving partially compiled files with this approach, although I haven't actually seen that behaviour. Your idea of a pre-compile makes a lot of sense, thanks.

I run a clean build many times per day -- at least every time I switch branches. In my experience the clojurescript compiler's ability to pick up side effects of multiple files at once, especially when macros are involved, is too unreliable to not do a clean build after switching branches.
