### ISSUE TITLE
Warn when project.clj changes

### ISSUE THREAD

**Issue by danielcompton** [bhauman/lein-figwheel#454]
Would it be a handy feature to warn the user when they change project.clj while Figwheel is running, and offer to restart the auto builder?

**Comment by bhauman** [comment]
This is an interesting feature, but I don't think I'm getting specifically what you are suggesting.

Restarting the autobuilder will only work if they change figwheel/cljs config data.   It won't work if they change dependencies.

Also the plumbing for asking for things in the REPL would be much more crazy than you might imagine, given that it needs to run in an NREPL context as well.  You may be imagining a popup in the browser.  That would work... 

But again the naive expectations might be that folks will be able to pull in new deps... because that is the most common reason for editing the project.clj.  The same is true for (reload-config) but only the more experienced users use that.

Of course we could check for changes in deps and let folks no that they need to restart from scratch...  But you have to wonder does it merit adding all this...

**Comment by danielcompton** [comment]
The most basic implementation of this would just be a warning when the project.clj has changed, and to tell warn the user to stop figwheel and restart it. That would solve the 80% case of changing deps and forgetting to restart figwheel. However if it's a lot of work, it's arguably not worth it.

**Comment by bhauman** [comment]
This could be done as an extra "component" the the figwheel system that gets added if there is a `project.clj` and then fires a warning notification if the `project.clj` changes and the dependencies changed.  It's not nothing to do this but certainly possible.  There will be the cost of having another watching process for that one file.

I'll take a PR for this ... but if you're not into let me know and we'll just close this.

**Comment by danielcompton** [comment]
I haven't thought about this much at all since I posted the issue, and I'm not feeling really compelled to provide a PR, so I'll close this for now.
