### ISSUE TITLE
Figwheel recompiles target even if changed files are not in dependencies

### ISSUE THREAD

**Issue by piranha** [bhauman/lein-figwheel#480]
Right now I start figwheel with two targets - one for the application itself and another for the service worker. Because of the limited Service Worker API I found no better way than set `:optimizations :simple` (instead of `:none`) for the compilation target so that I end up with a single file.

And now changes in any file of the application trigger compilation of both targets, which is unfortunate - service worker takes up to 15 seconds to compile, which slows down development quite drastically.

I could make another dev target in my Makefile which excludes worker, of course, but optimal way would be to make figwheel look at dependency graph of the target and rebuild it only when some dependency changes.

Does this make any sense?

**Comment by bhauman** [comment]
This was never a feature. However, I can see why you would want it, and why you might assume things should behave this way.

But ...

There is no root of a dependency graph if `:main` isn't being used. And regardless of the use of `:main` CLJS compiler just compiles all the immediately supplied source files so that they can be used in whatever way you see fit.  The "runtime require" is what determines the dependency graph.

One can easily have two or more root requires which determine the dependency graph.

You can also dynamically load a compiled file that is not in the dependency graph.

This is why figwheel behaves the way it does it because it mirrors the compiler.  The CLJS Compiler compiles a bag of assets and makes them available.  Any file in the :source-paths needs to trigger a compile because it is expected to be available in the resulting assets.  You will notice that your :simple compiled Service Worker will contain all the files in its :source-paths.  So technically your asset and its dependencies have changed.

Right now when you add a cljs file that isn't in the dependency tree it still gets compiled and syntax checked. This happens even when the file isn't required. This is helpful when mocking something up before loading it into your application.

There another catch 22 in that you need to compile the files in order to determine what the current dependency graph is.

This seems like a significant change in behavior that doesn't mirror the actual expected behavior of the compiler.

Since there is a ready solution in that you can use cljsbuild auto to build the Service Worker in a different process this seems like a dodgy feature.

**Comment by piranha** [comment]
Right, makes sense. I'll just create another target with compiles everything without Service Worker so that it's easier to develop the app itself.
