### ISSUE TITLE
In-memory injection of figwheel scripts disables analysis caching

### ISSUE THREAD

**Issue by rossj** [bhauman/lein-figwheel#489]
I've noticed a slowdown of `lein figwheel` startup times (on subsequent startups after an initial startup from clean) for our project after upgrading figwheel. Subsequent startup times for our project went from about 10 seconds to 50 seconds.

I believe that [this commit](https://github.com/bhauman/lein-figwheel/commit/e5caedaee3c1a8b9527e53269ec00256f2e1af43), which switches the injection of figwheel's scripts from a file to an in-memory source-form, is the culprit. It seems that clojurescript disables the use of the analysis cache if any source-form (non file) code is found.

This effect can be seen using the flappybird example, and setting `verbose: true`. Using figwheel `0.5.4-7`, I got an initial `lein figwheel` startup time of 17.4 seconds, and a subsequent startup time of 3.0 seconds, with many "Reading analysis cache..." lines in the verbose output the 2nd time around.

Switching to figwheel `0.5.5`, the initial startup time is 17.4 seconds, with subsequent startup time being 12.1 seconds and the verbose output indicating non-use of the analysis cache.

If this is a known effect or accepted tradeoff, feel free to close. I just couldn't find this discussed elsewhere.

Thanks!

**Comment by bhauman** [comment]
Hmmm, this is interesting.  It would be a shame to have to return to using the filesystem for injected dynamic code.  

Thanks for providing a test case, and finding a probable cause.

Path forward if this turns out to be true:
* Using the file system 
  (+) is simple
  (+) tried and true 
  (-) super stateful
* start using preloads and stop generating code entirely 
  (+) cache analysis will work
  (-)  relys on a macro reading the config from the cljs compilation env
  (-)  caching the script might lead to unwanted config caching??
        is this is a real problem? The idea is that the contents 
        of this file will change based on clojure runtime enviromental details, and clojurescript 
        will not know to recompile it, if there is a config change, and since the cache bridges running
        processes, figwheel client side configuration changes will not get picked up.
        Yeah this sounds like a problem. 
        Solution?: load the client side config from the server? Eliminates cached code novelty.
        Catch 22: The configuration contains the connection details.
