### ISSUE TITLE
Chrome warning

### ISSUE THREAD

**Issue by wnr** [bhauman/lein-figwheel#533]
I'm getting tons of these warning in my Chrome 56 console:

```
[Violation] Parser was blocked due to document.write(<script>)
base.js:1172 [Violation] Parser was blocked due to document.write(<script>)
goog.writeScriptSrcNode_ @ base.js:1172
goog.writeScriptTag_ @ base.js:1246
goog.importScript_ @ base.js:907
goog.writeScripts_ @ base.js:1420
goog.require @ base.js:673
(anonymous) @ index.html:11
2017-02-27 20:21:47.596 
```

I tried upgrading every dependency in my project, but the warnings are still there. I've been trying to google the problem as much as I can but I cannot find anything about it. Have you seen this? Sorry if this is not related to figwheel.

**Comment by bhauman** [comment]
I have not seen this. It seems like 

https://developers.google.com/web/updates/2016/08/removing-document-write

Are you connecting via 2G or a slow connection?

I have never seen this warning, but document.write is a fundamental way that Google Closure handles requires in :optimizations :none because it relies on the blocking behavior.

Not much for figwheel to do here it seems.

**Comment by wnr** [comment]
Okay, thanks.
