### ISSUE TITLE
vars defined in repl produce a compiler warning after reload but still work

### ISSUE THREAD

**Issue by MichaelBlume** [bhauman/lein-figwheel#535]
If I in-ns to a namespace defined in one of my source files, then define a new var from the repl, then edit and save that file, then refer to the new var from the repl, I get a compiler warning, even though the var is still accessible

```
cljs.user=> (in-ns 'my-test)
nil
dev:my-test=> (def foo [:bar :baz])
#'my-test/foo
***edit file and save***
dev:my-test=> foo
----  Compiler Warning on   <cljs form>   line:1  column:1  ----

  Use of undeclared Var my-test/foo

  1  foo
     ^--- 

----  Compiler Warning  ----
[:bar :baz]
```

**Comment by MichaelBlume** [comment]
This is probably related to #419 though in this case I'd much rather keep the REPL-defined var around

**Comment by bhauman** [comment]
Yes and that's probably warning worthy you are referring to a var that is not currently defined in the file.  And this happens because clojurescript is a compiled language and the compiler is throwing a warning based on its model of the universe.  The compiler has no knowledge of the runtime environment.  So what's confusing people is that the warning is not clearly labeled as a compiler warning? Or that folks are used to a repl that is reflecting a runtime environment?  The Clojure repl doesn't have warnings.
