### ISSUE TITLE
Detection of changes in files should be debounced

### ISSUE THREAD

**Issue by vemv** [bhauman/lein-figwheel#569]
Hi!

I think I've detected the following behavior:

* imagine I'm editing the cljs files A, B, C in my editor.
* I save all three files at the same time, with an editor command.
* Consequently, files are written to the filesystem at essentially the same time, but differing a few ms or so.
* Figwheel is watching for changes. As soon as the first file updated in the filesystem (let say it's file A out of A B and C), Fighwheel says "let's recompile and reload file A into the browser"
* Immediately after, Fighwheel says "let's recompile and reload file B into the browser" and "let's recompile and reload file C into the browser"

The consequence is that I see A loaded first, then B, then C, instead of a consistent, atomic loading of A B and C into the new compiled js.

For most cases, this doesn't matter a lot (I think), because Figwheel will just reload the app 3 times very briefly and the user won't notice a thing.

But, this 'non-debounced' approach is suboptimal per se, and also affects me directly because I have the following setup:

```clojure
;; project.clj:

:figwheel {:on-jsload "foo.bar.hard-reload" ...

;; foo.bar.cljs:

(defn hard-reload []
  (.reload js/location true))
```

With hard reloading in play, I start getting inconsistency errors that won't be automatically recovered (I have to manually reload again).

I hope the described issue is accurate!

Cheers - Victor

**Comment by bhauman** [comment]
We are currently waiting 50ms and gathering all the changes that happen in that period of time.

https://github.com/bhauman/lein-figwheel/blob/master/sidecar/src/figwheel_sidecar/watching.clj#L27

Waiting longer than 100ms affects the final response time of figwheel. So that points to this being configurable option.

I'm willing to take a PR for a configuration option. But I think the assumption that the save time is only differing by a few ms may be off.
