### ISSUE TITLE
support for multiple build profiles

### ISSUE THREAD

**Issue by ul** [bhauman/lein-figwheel#57]
`lein-cljsbuild` supports `lein cljsbuild auto main other`, may be figwheel also should?

**Comment by bhauman** [comment]
Hey guys I deployed lein-figwheel/0.2.1-SNAPSHOT that supports multiple builds.

I'd love for you to try it out

It's optional but helpful to use a `:build-id` on the client config.  So that the client is smarter about filtering messages for the build under focus.  It should work without it but there is potential of multiple reloads for a changed file in certain situations.

**Comment by ul** [comment]
Man, this is a real New Year gift. Worked a little bit with it today, didn't notice any issues.

**Comment by bhauman** [comment]
Glad its working for you. :)
