### ISSUE TITLE
Plugin includes extra sources that sidecar doesn't

### ISSUE THREAD

**Issue by baritonehands** [bhauman/lein-figwheel#655]
I have a project with multiple cljs/figwheel builds and I'm experiencing weird behavior where the Cursive REPL figwheel and cljsbuild work fine, but lein figwheel includes sources that it shouldn't.

My project: https://github.com/baritonehands/gccg-react

When I run from Cursive REPL using figwheel-sidecar.repl-api, everything seems to work fine. It also works fine when I do `lein cljsbuild once web`. I used code from the generated re-natal project to start figwheel from Cursive: https://github.com/baritonehands/gccg-react/blob/master/src/common_dev/user.clj. I call `(start-figwheel "web")`.

When I run `lein figwheel web` it includes some cljs files that are not in the list. If you run that command and look in target/cljsbuild/public/js/out/reagent/**/*.cljs you'll see some stubs where there should be real code. I stub those out only for my src/mobile directory for react-native builds, but somehow they are included in my web build despite not having that directory included. I also noticed that target/cljsbuild/ios and android are created (empty) despite not being in the source paths.

**Comment by bhauman** [comment]
If you have source-paths that point conflicting namespaces.

You need to specify `:load-all-builds false` in the `:figwheel` config.

https://github.com/bhauman/lein-figwheel/blob/master/sidecar/src/figwheel_sidecar/schemas/config.clj#L299

I know this seems like surprising behavior, but its inherited from cljsbuild (so I'm not sure why cljsbuild worked for you, maybe path order?, or its behavior has changed). Figwheel needs all the paths on the classpath in order to change which builds are being built while it's running. The plugin has to set up the classpath before launching figwheel so ...

Sorry for the confusion.

**Comment by baritonehands** [comment]
Aha, simple enough, that worked. Thanks for the quick response.
