### ISSUE TITLE
:notify-command output hidden

### ISSUE THREAD

**Issue by nathants** [bhauman/lein-figwheel#67]
when upgrading from 1.7->2.0 the output of :notify-command is no longer show in the console when using lein figwheel.

**Comment by bhauman** [comment]
Yeah support for notify dropped from Figwheel (not cljsbuild), I moved away from cljsbuild to speed up builds when editing clj files.  I am planning on adding it notify in.

Is it something that you are missing? What are you using it for?

**Comment by nathants** [comment]
i miss it!!!

:)

i use a single lein instance to compile my test and dev code. i instantiate it with lein figwheel, and use the notify-command to auto run tests. 

https://github.com/nathants/template.cljs_web/blob/master/src/leiningen/new/cljs_web/project.clj#L16

**Comment by bhauman** [comment]
Alright try 0.2.2-SNAPSHOT.  I added notify-command back.  It is different from cljsbuild in that it only notifies on a successful compile. Cljsbuild notified for every event.  Since the most common use case is testing I think this is better.

Maybe I should add an explicit :after-compile-command to make this clearer.

Also you will probably be the first to use figwheel with the new repl integration.  
Figwheel now launches a first class cljs repl that shares compiler information with the autobuilder which means the repl be aware of your code changes as you make them.  So that when you do an (in-ns ) everything that is in the ns will be available without requirement if the ns is loaded in your app.

So you can rock with the repl without using load-namspace or require very often or at all.

The figwheel autobuilder output is redirected to a file figwheel_server.log

You can disable the repl with `:repl false` in the :figwheel config in project.clj.
You can config the logfile name with `:server-logfile tmp/logs/name-of-file.log` 

If you `brew install rlwrap` you can run figwheel like this `rlwrap lein figwheel`

This will require clojurescript 2665.  Does that work for you? I can patch an earlier release of figwheel if you need it.

I would love feedback on the repl.  Its a big change but I think its a sane and needed default behavior.

**Comment by cichli** [comment]
REPL change is very exciting - I'll also give it a try this weekend. Thanks!

**Comment by nathants** [comment]
awesome! will try tonight...

**Comment by nathants** [comment]
dude, awesome work! i especially like how if you disable the repl, the :notify-command output streams instead of going to that log. exactly what i wanted!!!

repl is really cool. can this work with cider-jack-in and other nrepl friends?

and 2665 is fine :)

**Comment by bhauman** [comment]
You probably already know this. But you can do a `tail -f` on the logfile to monitor its output and still use the repl.

**Comment by nathants** [comment]
yeah, but thanks for the tip :)

not really using a repl much for cljs, other than figwheel's normal file loading repl-ish thingy. i was recently trying out emacs integration with cider and browser repl for things like code completion and go to definition. its getting close, but not quite there. for me at least.

maybe by the time it gets there, i can can cider-jack-in to a figwheel repl. that will be a party i'd like to attend...

**Comment by bhauman** [comment]
yeah the whole REPL problem is what caused me to write figwheel in the
first place.

On Fri, Jan 16, 2015 at 3:56 PM, nathan todd.stone <notifications@github.com
